### PR TITLE
More details about adding a new stemmer.

### PR DESCRIPTION
**Pull request by jan-tosovsky-cz**
For my use case - replacing one stemmer with advanced one - I had to go through all the process: creating Java stemmer from SBL algorithm, integrating it into the Java bundle, tweaking the bundle and then finally generating JavaScript files. I've refactored Readme completely - to split the process into individual steps and provide more details for each of them.

### CODE REVIEW

**Comment by mazko** [comment]
Thank you. Can we find some place for Quick Start (or env check) somewhere:

```
git clone https://github.com/mazko/jssnowball.git
cd jssnowball/
make bundle
git checkout -- js_snowball/eclipse/
make bundle
# edit js_snowball/lib/snowball.bundle.java :es6: code :end:
npm i -g babel-cli esjava
npm i babel-preset-es2015 babel-plugin-transform-es2015-modules-umd
make esjava
```

**Comment by jan-tosovsky-cz** [comment]
Sure, originally I had another **How to build** section for this, besides *Adding a new stemmer*. It turned out to be just simplified variant of same procedure so I removed it (expecting end user will skip unnecessary steps).

I have an idea how to integrate it. But I am afraid I still do not understand the following blocks, i.e. why `make bundle` is executed twice:
```
git clone https://github.com/mazko/jssnowball.git
cd jssnowball/
make bundle
```
```
git checkout -- js_snowball/eclipse/
make bundle
```
Is that second call necessary? Can you elaborate the purpose a bit?

Thanks.

**Comment by mazko** [comment]
`make bundle` twice is just workaround, it just works. The only purpose is somebody has to refactor makefile and split `make bundle` to more steps )

**Comment by jan-tosovsky-cz** [comment]
I considered that second `make bundle` to be a redundant step. But I did that procedure again and finally I am able to see some difference. In the first run Java stemmers are built from SBL files in 

- `snowball_cache/out/java/org/tartarus/snowball/ext` and 
- `js_snowball/eclipse/src/org/tartarus/snowball/ext`

That `snowball.bundle.java` bundle is hence built not from the original `js_snowball/eclipse` folder, but from the regenerated one.  So now it is clear why this folder has to be checked out again from GitHub. 

But the is one remaining magic to me. Why the second run doesn't trigger regenerating Java code like in the first run?

**Comment by mazko** [comment]
> But the is one remaining magic to me. Why the second run doesn't trigger regenerating Java code like in the first run?

I am not sure (this was a long time ago), but I guess `$(java_src_out)/$(java_src_scheme)/%Stemmer.java`  remains unchanged https://github.com/mazko/jssnowball/blob/master/GNUmakefile#L195 and thus makefile does not trigger this rule

**Pull request merged**
